#!/bin/bash
# ============================================================================
# Apply Timezone Migration to Supabase
# ============================================================================

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   📅 TIMEZONE MIGRATION - London Default Setup            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will guide you through applying the timezone migration."
echo ""
echo "📋 STEPS TO APPLY:"
echo ""
echo "1️⃣  Open Supabase Dashboard"
echo "   👉 https://supabase.com/dashboard"
echo ""
echo "2️⃣  Navigate to SQL Editor"
echo "   Projects → [Your Project] → SQL Editor"
echo ""
echo "3️⃣  Create New Query"
echo "   Click '+ New Query' button"
echo ""
echo "4️⃣  Copy Migration SQL"
echo "   File: migrations/set_default_timezone_london.sql"
echo ""
echo "5️⃣  Paste and Run"
echo "   Paste the SQL content and click 'Run' or press Cmd/Ctrl + Enter"
echo ""
echo "6️⃣  Verify Success"
echo "   Check for success messages in the output panel"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ WHAT THIS MIGRATION DOES:"
echo ""
echo "  • Changes default timezone from America/New_York to Europe/London"
echo "  • Updates the database schema default value"
echo "  • Updates the handle_new_user() trigger function"
echo "  • All new signups will use London timezone"
echo "  • Existing users remain unchanged"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 VERIFICATION:"
echo ""
echo "After running the migration, verify with this query:"
echo ""
echo "  SELECT column_default"
echo "  FROM information_schema.columns"
echo "  WHERE table_name = 'users_profile'"
echo "    AND column_name = 'time_zone';"
echo ""
echo "Expected result: 'Europe/London'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 TEST THE CHANGE:"
echo ""
echo "1. Sign up a new test user"
echo "2. Confirm email and log in"
echo "3. Go to Settings → Profile"
echo "4. Verify timezone shows 'Europe/London (GMT/BST)'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 DOCUMENTATION:"
echo ""
echo "  Full documentation: TIMEZONE_CHANGE.md"
echo "  Migration file:     migrations/set_default_timezone_london.sql"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Need help? Check TIMEZONE_CHANGE.md for detailed instructions."
echo ""
